#pragma config(Sensor, dgtl1,  Top,            sensorTouch)
#pragma config(Sensor, dgtl12, Over,           sensorLEDtoVCC)
#pragma config(Motor,  port1,           LDrive,        tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           LiftR,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LiftL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LDriveB,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RDriveB,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          RDrive,        tmotorVex393_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool auto = false; //Bool containing if autopilot is enabled
bool overset = false;

task drive()
{
	int threshold = 10;	//Deadzone for joystick. Default=10

	while(true)
	{

		if(auto == false) //Check if autopilot is enabled
		{

			if(abs(vexRT[Ch3]) > threshold || abs(vexRT[Ch4]) > threshold) //Check if the joystick is past the deadzone
			{
				motor[LDrive]= vexRT[Ch3]+vexRT[Ch4];
				motor[RDrive]= vexRT[Ch3]-vexRT[Ch4];
				motor[LDriveB]= vexRT[Ch3]+vexRT[Ch4];
				motor[RDriveB]= vexRT[Ch3]-vexRT[Ch4];

			}
			else
	    {
	      motor[LDrive]  = 0;
	      motor[RDrive]  = 0;
	      motor[LDriveB]  = 0;
	      motor[RDriveB]  = 0;
	    }

		}
	}
}

task fork()
{
	int threshold = 10; //Deadzone for joystick. Default=10

	while(true)
	{
		if(vexRT[Ch2] > 0 && SensorValue[Top] == 1 && overset == false)
		{
			motor[LiftR]  = 0;
      motor[LiftL]  = 0;
		}

		else
		{
			if(abs(vexRT[Ch2]) > threshold)
			{
				motor[LiftR]= vexRT[Ch2];
				motor[LiftL]= -vexRT[Ch2];
			}

			else
			{
		     motor[LiftR]  = 0;
		     motor[LiftL]  = 0;
		  }
		}
	}
}

task override()
{
	while(true)
	{
		if(vexRT[Btn5U] == 1 && overset == false)
		{
			overset=true;
			waitUntil(vexRT[Btn5U] == 0);
		}

		if(vexRT[Btn5U] == 1 && overset == true)
		{
			overset=false;
			waitUntil(vexRT[Btn5U] == 0);
		}

		if(overset==false)
		{
			SensorValue[Over]=0;
		}

		else
		{
			SensorValue[Over]=1;
		}
	}
}

task main()
{
	startTask(drive);
	startTask(fork);
	startTask(override);

	while(true)
	{

	}
}
