#pragma config(Motor,  port1,           Rot1,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Arm2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           Arm3,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Rot2,          tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task rot()
{
	while(true)
	{
		motor[Rot1] = vexRT[Ch4Xmtr2];
		motor[Rot2] = -vexRT[Ch4Xmtr2];
	}
}

task arm()
{
		while(true)
		{
			motor[Arm1] = -vexRT[Ch3Xmtr2]*abs(vexRT[Ch3Xmtr2])/255;
			motor[Arm2] = -vexRT[Ch3Xmtr2]*abs(vexRT[Ch3Xmtr2])/255;
			motor[Arm3] = -vexRT[Ch2Xmtr2];
			motor[Claw] = vexRT[Ch1Xmtr2];
		}
}

task drive()
{

}

task main()
{
	startTask(rot);
	startTask(arm);
	startTask(drive);
	while(true)
	{}
}
