#pragma config(Sensor, dgtl1,  LED_1,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           frontRight,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           backRight,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           frontLeft,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           motor6,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           motor7,        tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Mecanum Drive - Basic
- This program allows you to remotely control a robot with mecanum wheels.
- The left joystick Y-axis controls the robot's forward and backward movement.
- The left joystick X-axis controls the robot's left and right movement.
- The right joystick X-axis controls the robot's rotation.

[I/O Port]          [Name]              [Type]                [Description]
Motor Port 2        frontRight          VEX Motor             Front Right motor
Motor Port 3        backRight           VEX Motor             Back Right motor
Motor Port 4        frontLeft           VEX Motor             Front Left motor
Motor Port 5        backLeft            VEX Motor             Back Left motor
----------------------------------------------------------------------------------------------------*/

task flashLed_1()
{
    while( true )
        {
        // output to 1
        SensorValue[LED_1] = 1;
        wait1Msec( 500 );

        // output to 0
        SensorValue[LED_1] = 0;
        wait1Msec( 500 );
        }
}

task main()
{
  //Loop Forever

	StartTask( flashLed_1 );

	while(true)
	{

		motor[motor6] = 127;
		motor[motor7] = 127;

		//Remote Control Commands
    motor[frontRight] = vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];
    motor[backRight] =  -vexRT[Ch3] + vexRT[Ch1] + vexRT[Ch4];
    motor[frontLeft] = vexRT[Ch3] + vexRT[Ch1] + vexRT[Ch4];
    motor[backLeft] =  -vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];


	}

}


int W1 = 127;
	int W2 = 127;

	vexRT[Ch2Xmtr2]
