#pragma config(Sensor, dgtl1,  LED_1,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port1,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           backLeft,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	int X2 = 0, Y1 = 0, X1 = 0, threshold = 15;

	while(true)
	{

	if(abs(vexRT[Ch3]) > threshold)
      Y1 = vexRT[Ch3];
    else
      Y1 = 0;
    //Create "deadzone" for X1/Ch4
    if(abs(vexRT[Ch4]) > threshold)
      X1 = vexRT[Ch4];
    else
      X1 = 0;
    //Create "deadzone" for X2/Ch1
    if(abs(vexRT[Ch1]) > threshold)
      X2 = vexRT[Ch1];
    else
      X2 = 0;



		//Remote Control Commands
    motor[frontRight] = -Y1 + X2 + X1;
    motor[backRight] =  -Y1 + X2 - X1;
    motor[frontLeft] = Y1 + X2 - X1;
    motor[backLeft] =  Y1 + X2 + X1;


	}

}
