#pragma config(Motor,  port1,           motor1,        tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port9,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          motor2,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task scoop()
{

}

task drive()
{
	while(true)
	{
		motor[frontRight] = -vexRT[Ch3] - vexRT[Ch1] - vexRT[Ch4];
    motor[backRight] =  -vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];
    motor[frontLeft] = -vexRT[Ch3] + vexRT[Ch1] + vexRT[Ch4];
    motor[backLeft] =  -vexRT[Ch3] + vexRT[Ch1] - vexRT[Ch4];

	}

}

task main()
{
	startTask(scoop);
	startTask(drive);

	while(true)
	{
	motor[motor1] = 127;
	motor[motor2] = 127;

	}


}
