#pragma config(Sensor, dgtl1,  led,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           Chain,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Launcher,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Launcher2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Test,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Roller,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task Shoot()//r stands for robert, AKA the person using the partner controller
{
	while(true)
	{
		if(vexRT[Btn6UXmtr2] == 1)
		{
			motor[Launcher]=127;
			motor[Launcher2]=127;
		}
		else
		{
			motor[Launcher]=0;
			motor[Launcher2]=0;
		}
	}
}

task Scoop()
{
	while(true)
	{
		motor[Chain] = vexRT[Ch3Xmtr2];
		motor[Roller] = vexRT[Ch3Xmtr2];
	}
}

task Drive()
{
	while(true)
	{
		motor[frontRight] = vexRT[Ch3] - vexRT[Ch1] - vexRT[Ch4];
    motor[backRight] =  vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];
    motor[frontLeft] = -vexRT[Ch3] - vexRT[Ch1] - vexRT[Ch4];
    motor[backLeft] =  -vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];

	}

}


task main()
{
	startTask(Scoop);
	startTask(Shoot);
	startTask(Drive);
	clearLCDLine(0);
	clearLCDLine(1);

	while(true)
	{
		displayLCDPos(0, 0);
		displayNextLCDString("Move Bitch");
		displayLCDPos(1, 0);
		displayNextLCDString("get out the way");

	}
}
