#pragma config(Motor,  port4,           Drive,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Drive2,        tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool auto = false; //Bool containing if autopilot is enabled

task drive()
{
	int threshold = 10;	//Deadzone for joystick. Default=10

	while(true)
	{

		if(auto == false) //Check if autopilot is enabled
		{

			if(abs(vexRT[Ch3]) > threshold) //Check if the joystick is past the deadzone
			{
				motor[Drive]= -vexRT[Ch3];
			}
			else
	    {
	      motor[Drive]  = 0;
	      motor[Drive2]  = 0;
	    }

		}
	}
}

task main()
{
	startTask(drive);

	while(true)
	{

	}
}
