#pragma config(Motor,  port6,           RDrive,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LDrive,        tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool auto = false; //Bool containing if autopilot is enabled

task drive()
{
	int threshold = 10;	//Deadzone for joystick. Default=10

	while(true)
	{

		if(auto == false) //Check if autopilot is enabled
		{

			if(abs(vexRT[Ch3]) > threshold || abs(vexRT[Ch4]) > threshold) //Check if the joystick is past the deadzone
			{
				motor[LDrive]= vexRT[Ch3];
				motor[RDrive]= vexRT[Ch2];
			}
			else
	    {
	      motor[LDrive]  = 0;
	      motor[RDrive]  = 0;
	    }

		}
	}
}

task main()
{
	startTask(drive);

	while(true)
	{

	}
}
