#pragma config(Motor,  port1,           RTurn,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port6,           RDrive,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LDrive,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          LTurn,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool auto = false; //Bool containing if autopilot is enabled
int count = 50;



/////////////////
//--Functions--//
/////////////////

void rotLeft()
{
	if(count < 127)
	{
		motor[LTurn]= -count;
		motor[RTurn]= -count;
		count++;
		delay(10);
	}

	else
	{
		motor[LTurn]= -127;
		motor[RTurn]= -127;
	}
}

void rotRight()
{
	if(count < 127)
	{
		motor[LTurn]= count;
		motor[RTurn]= count;
		count++;
		delay(10);
	}

	else
	{
		motor[LTurn]= 127;
		motor[RTurn]= 127;
	}
}



/////////////////
//----Tasks----//
/////////////////

task drive()
{
	int threshold = 10;	//Deadzone for joystick. Default=10

	while(true)
	{

		if(auto == false) //Check if autopilot is enabled
		{

			if(abs(vexRT[Ch2]) > threshold || abs(vexRT[Ch3]) > threshold) //Check if the joystick is past the deadzone
			{
				motor[LDrive]= vexRT[Ch2];
				motor[RDrive]= vexRT[Ch3];
			}
			else
	    {
	      motor[LDrive]  = 0;
	      motor[RDrive]  = 0;
	    }

		}
	}
}

task rot()
{
	while(true)
	{
		if(vexRT[Btn5U] == 1)
		{
			rotLeft();
		}

		else if(vexRT[Btn6U] == 1)
		{
			rotRight();
		}

		else if(vexRT[Btn5UXmtr2] == 1)
		{
			rotLeft();
		}

		else if(vexRT[Btn6UXmtr2] == 1)
		{
			rotRight();
		}

		else
		{
			motor[LTurn]= 0;
			motor[RTurn]= 0;
			count = 50;
		}
	}
}

task arm()
{
	while(true)
	{

	}
}

//////////////////
//-----Main-----//
//////////////////

task main()
{
	startTask(drive);
	startTask(rot);
	startTask(arm);

	while(true)
	{

	}
}
