#pragma config(Sensor, in1,    Gyro,           sensorGyro)
#pragma config(Motor,  port3,           UpArm,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RLowArm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LLowArm,       tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int value = 0;
int zero = 0;

task control()
{
	while(true)
	{
		motor[LLowArm]= -vexRT[Ch3];
		motor[RLowArm]= -vexRT[Ch3];

	}
}

task angle()
{
	while(true)
		{
		motor[UpArm]= -vexRT[Ch2];
		if(abs(vexRT[Ch2]) > 10)
		{
			zero = SensorValue[Gyro];
		}
	}
}

task main()
{
	startTask(control);
	startTask(angle);

	SensorType[Gyro] = sensorNone;
	wait1Msec(1000);
	//Reconfigure Analog Port 8 as a Gyro sensor and allow time for ROBOTC to calibrate it
	SensorType[Gyro] = sensorGyro;
	wait1Msec(2000);

	zero = SensorValue[Gyro];

	while(true)
	{
		value = SensorValue[Gyro];
		if(value<zero-30 && abs(vexRT[Ch2]) < 10)
		{
			motor[UpArm]= 127;
		}

		else if(value>zero+30 && abs(vexRT[Ch2]) < 10)
		{
			motor[UpArm]= -127;
		}

		else
		{
			motor[UpArm]= -20;
		}
	}
}
